### PR TITLE
Pull request#5

### PR DESCRIPTION
**Pull request by areeba-waheed**

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @LuanTa-CSUN

**Comment by kyledewey** [comment]
Additionally assigned @AshotC

**Review by LuanTa-CSUN — APPROVED** [review]
The code was written in a clear and readable manner. Nice job!

**Review by AshotC — APPROVED** [review]
Some of your function names seem a bit inconsistent, try to find some uniform format to more clearly separate actual tests and other bits of code. More comments never hurt either. Otherwise everything looks fine.

**Pull request merged**
