### PR TITLE
Pull Request #2

### PR DESCRIPTION
**Pull request by areeba-waheed**

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @jenmancia

**Comment by kyledewey** [comment]
Additional review requested from @mj-shi

**Review by mj-shi — APPROVED** [review]
Detailed documentation regarding plan and system.
New Java file code is well spaced and indented.

**Review by jennmancia — COMMENTED** [review]
Everything is great. Good documentation on what has been done and very legible code. I like how it's structured.

**Pull request merged**
